#!/bin/bash

# The absolute path to the factorio directory
FACTORIO_PATH=/opt/factorio

# The latency expected between peers (milliseconds)
# Try to set this to the highest latency + 30
# If Peer A and B have a latency of 100 between each other
# set this to 130
LATENCY=130

# The number of minutes between each autosave
AUTOSAVE_INTERVAL=10

# The number of autosaves to use for rotation
AUTOSAVE_SLOTS=3

#
# narcotiq made a sweet update script for factorio and by cloning into this
# you can simply run "factorio update" provided you configure the below arguments
# To install the updater:
#
# git clone https://github.com/narc0tiq/factorio-updater
#

# absolute path to the factorio-updater script
# UPDATE_SCRIPT=/opt/factorio-updater/update_factorio.py

# Extras
# Additional binary arguments, these will be sent to the binary when issuing the "start" command
# EXTRA_BINARGS="--disallow-commands"
